### ISSUE TITLE
[FEATURE] Add Console 키보드 input

### ISSUE THREAD

**Issue by jhshin29** [jhshin29/coins-project#11]
- [x] 콘솔창에서 키보드 입력할 수 있는 메뉴 만들기
- [x] Order 예외처리
- [x] Member 예외처리
- [x] Coin 예외처리

**Comment by seeun214** [comment]
### **✔️Member예외처리**

- [x] 회원가입 시 중복 아이디일 경우 메시지 출력
- [x] update, delete 에서 존재하지 않는 id 입력 시 예외처리
